export type Locale = "ar" | "en";

export const locales: Locale[] = ["ar", "en"];

export const content = {
  ar: {
    meta: {
      title: "فَهْم | FAHM — منصة الذكاء الاصطناعي للتعلّم التكيفي لذوي الإعاقة",
      description:
        "فَهْم منصة تعليمية ذكية تستخدم الذكاء الاصطناعي لإعادة تكييف المحتوى التعليمي بما يتناسب مع احتياجات الطلاب ذوي الإعاقة.",
    },
    skip: "تخطَّ إلى المحتوى",
    nav: {
      open: "فتح القائمة",
      close: "إغلاق القائمة",
      menu: "القائمة",
      items: [
        { href: "#about", label: "النبذة" },
        { href: "#problem", label: "المشكلة" },
        { href: "#solution", label: "الحل" },
        { href: "#features", label: "المزايا" },
        { href: "#how-it-works", label: "كيف يعمل" },
        { href: "#impact", label: "الأثر" },
        { href: "#vision", label: "الرؤية" },
      ],
    },
    lang: {
      switchTo: "English",
      switchAria: "Switch to English",
      current: "العربية",
    },
    hero: {
      brandAr: "فَهْم",
      brandEn: "FAHM",
      eyebrow: "منصة تعليمية ذكية",
      subtitle: "منصة الذكاء الاصطناعي للتعلّم التكيفي لذوي الإعاقة",
      slogan: "كل طفل يستحق أن يفهم ويتعلم وينجح، مهما اختلفت طريقته في التعلم.",
      primaryCta: "تعرّف على فَهْم",
      secondaryCta: "للمدارس والشركاء",
    },
    about: {
      kicker: "نبذة عن المشروع",
      title: "المعرفة تتكيّف مع الطالب، لا العكس",
      p1: "فَهْم (FAHM) منصة تعليمية ذكية تستخدم الذكاء الاصطناعي لإعادة تكييف المحتوى التعليمي بما يتناسب مع احتياجات الطلاب ذوي الإعاقة.",
      p2: "بدل أن يضطر الطالب إلى التكيف مع الكتاب، يقوم فَهْم بتكييف المعرفة مع الطالب.",
      p3: "يصور الطالب صفحة من كتابه أو يرفعها إلى المنصة، ثم يقوم النظام بفهم النصوص والصور والرسومات التعليمية وإعادة تقديم المحتوى بطريقة أكثر وضوحًا وملاءمة لاحتياجه.",
    },
    problem: {
      kicker: "المشكلة",
      title: "الكتاب واحد… والاحتياجات مختلفة",
      lead: "الكتب الدراسية مصممة غالبًا بطريقة موحدة، بينما تختلف قدرات واحتياجات الطلاب.",
      intro: "قد يواجه الطالب ذو الإعاقة صعوبة في:",
      items: [
        "قراءة النصوص الكثيفة.",
        "فهم الرسومات والمخططات.",
        "التركيز على المعلومات الأساسية.",
        "الوصول إلى المحتوى دون مساعدة الآخرين.",
        "التعامل مع المحتوى بالطريقة التقليدية.",
      ],
      closer: "المشكلة ليست في قدرة الطالب على التعلم، بل في طريقة تقديم المعرفة له.",
    },
    solution: {
      kicker: "الحل",
      title: "من صفحة الكتاب إلى تجربة تعلم ميسرة",
      lead: "يحوّل فَهْم الصفحة التعليمية إلى تجربة تعلم تكيفية من خلال:",
      steps: [
        { title: "صورة الكتاب", hint: "تصوير أو رفع الصفحة" },
        { title: "فهم المحتوى", hint: "نص وصور ورسوم" },
        { title: "تحليل احتياج الطالب", hint: "وفق طريقته في التعلّم" },
        { title: "إعادة تكييف المعرفة", hint: "بدون تغيير المنهج" },
        { title: "تجربة تعلم ميسرة", hint: "قراءة أو استماع أو تفاعل" },
      ],
      note: "دون الحاجة إلى إعادة تصميم الكتاب أو تغيير المنهج الدراسي.",
    },
    audiences: {
      kicker: "الفئات المستهدفة",
      title: "صُمم لمن تختلف طريقته في الوصول إلى المعرفة",
      items: [
        "الطلاب ذوو الإعاقة البصرية.",
        "الطلاب ذوو عسر القراءة.",
        "الطلاب ذوو اضطراب فرط الحركة وتشتت الانتباه.",
        "الطلاب ذوو صعوبات التعلم.",
      ],
      note: "ويمكن مستقبلاً توسيعه ليخدم فئات أوسع من المتعلمين.",
    },
    features: {
      kicker: "المزايا الأساسية",
      title: "سبع قدرات تصنع تجربة فهم كاملة",
      items: [
        {
          num: "01",
          title: "الفهم الذكي",
          body: "يحلل فَهْم النصوص والصور والرسومات التعليمية، وليس مجرد استخراج النص.",
        },
        {
          num: "02",
          title: "التعلم التكيفي",
          body: "يعيد تقديم المحتوى وفق احتياجات الطالب بدل تقديم تجربة واحدة للجميع.",
        },
        {
          num: "03",
          title: "الوصول الصوتي",
          body: "تحويل المحتوى إلى شرح صوتي طبيعي باللغة العربية باستخدام تقنيات تحويل النص إلى كلام.",
        },
        {
          num: "04",
          title: "التلخيص الذكي",
          body: "اختصار الدروس والمحتوى المعقد إلى نقاط واضحة وسهلة الفهم.",
        },
        {
          num: "05",
          title: "القراءة الميسرة",
          body: "إعادة تنسيق المحتوى لتحسين قابلية القراءة، مع دعم خصائص مناسبة للطلاب ذوي عسر القراءة.",
        },
        {
          num: "06",
          title: "فهم الصور التعليمية",
          body: "تحليل الرسومات والمخططات والصور وشرح معناها للطالب بطريقة مبسطة.",
        },
        {
          num: "07",
          title: "المساعد الذكي",
          body: "إتاحة التفاعل مع المحتوى وطلب التوضيح أو التبسيط أو الأمثلة.",
        },
      ],
    },
    how: {
      kicker: "كيف يعمل النظام؟",
      title: "خمس خطوات من الصفحة إلى الفهم",
      steps: [
        "يقوم الطالب بتصوير صفحة الكتاب أو رفع صورة لها.",
        "يحلل الذكاء الاصطناعي النص والصور والعناصر البصرية.",
        "يفهم النظام المحتوى التعليمي ويحدد العناصر المهمة.",
        "تتم إعادة تكييف المحتوى حسب احتياجات الطالب.",
        "يحصل الطالب على تجربة تعليمية ميسرة يمكن قراءتها أو الاستماع إليها أو التفاعل معها.",
      ],
    },
    tech: {
      kicker: "التقنيات",
      title: "بنية تجمع بين الرؤية واللغة والتعلّم التكيفي",
      items: [
        "Generative AI",
        "Computer Vision",
        "OCR",
        "Natural Language Processing",
        "Text-to-Speech",
        "Adaptive Learning",
        "Large Language Models",
      ],
      stackLabel: "Stack",
      stack:
        "Next.js + TypeScript + Tailwind CSS + Python/FastAPI + AI APIs + ElevenLabs",
    },
    difference: {
      kicker: "ما الذي يجعل فَهْم مختلفًا؟",
      title: "من قراءة المحتوى إلى محرك تعلم تكيفي",
      traditionalLead: "معظم أدوات الوصول التقليدية تركز على قراءة المحتوى.",
      fahmLead: "أما فَهْم فيركز على فهم المحتوى وإعادة تكييفه.",
      instead: "بدل",
      offers: "يقدم",
      traditionalPath: ["Read", "Listen"],
      fahmPath: ["See", "Understand", "Adapt", "Learn"],
      closer: "وهذا يحول المنصة من قارئ محتوى إلى محرك تعلم تكيفي.",
      traditionalLabel: "الأدوات التقليدية",
      fahmLabel: "فَهْم",
    },
    innovation: {
      kicker: "الابتكار",
      title: "صفحة واحدة… وتجربة مختلفة لكل طالب",
      lead: "الابتكار الأساسي في فَهْم هو الجمع بين:",
      parts: [
        "فهم النص",
        "فهم الصورة",
        "الذكاء الاصطناعي التوليدي",
        "التخصيص",
        "الوصول الميسر",
      ],
      join: "داخل تجربة واحدة.",
      closer: "فالصفحة نفسها يمكن أن تتحول إلى تجربة مختلفة حسب احتياج الطالب.",
    },
    impact: {
      kicker: "الأثر المتوقع",
      title: "استقلالية أكبر… وفهم أقرب",
      items: [
        "تعزيز استقلالية الطلاب ذوي الإعاقة.",
        "تسهيل الوصول إلى المعرفة.",
        "تحسين فهم المحتوى التعليمي.",
        "تقليل الاعتماد على المساعدة البشرية.",
        "دعم التعليم الشامل.",
        "تقليل الفجوة بين الطالب والمحتوى.",
      ],
      resultLabel: "النتيجة المستهدفة",
      result: "طالب يستطيع الوصول إلى المعرفة وفهمها بطريقة تناسبه.",
    },
    mvp: {
      kicker: "النموذج الأولي MVP",
      title: "نموذج عامل لإثبات قابلية الفكرة",
      lead: "تم تطوير نموذج أولي عامل لإثبات قابلية الفكرة للتطبيق.",
      includes: "يشمل النموذج:",
      items: [
        "رفع صفحات الكتب.",
        "تحليل المحتوى بالذكاء الاصطناعي.",
        "فهم النصوص والعناصر البصرية.",
        "إعادة صياغة المحتوى.",
        "التلخيص.",
        "الإخراج الصوتي.",
        "تجربة تعليمية ميسرة.",
      ],
      closer:
        "ويُستخدم النموذج لإثبات الفكرة واختبار تجربة المستخدم قبل التوسع إلى منصة تعليمية متكاملة.",
    },
    business: {
      kicker: "نموذج العمل",
      title: "اشتراك مؤسسي… ثم شبكة أوسع",
      primary: "اشتراك سنوي للمؤسسات التعليمية",
      expand: "مع إمكانية التوسع مستقبلًا إلى:",
      items: [
        "التراخيص المؤسسية.",
        "الشراكات الحكومية.",
        "التكامل مع منصات التعليم.",
        "حلول مخصصة للمدارس ومراكز التربية الخاصة.",
      ],
    },
    roadmap: {
      kicker: "استراتيجية التوسع",
      title: "من عينة محددة إلى المنطقة العربية",
      stages: [
        "اختبار المنصة مع عينة محددة من الطلاب ذوي الإعاقة.",
        "التوسع إلى مدارس الدمج ومراكز التربية الخاصة.",
        "التوسع على مستوى المملكة العربية السعودية.",
        "التكامل مع المنظومة التعليمية الوطنية.",
        "التوسع في دول الخليج والمنطقة العربية.",
      ],
    },
    metrics: {
      kicker: "قياس الأثر",
      title: "ما نقيسه لنعرف أن الفهم يحدث",
      items: [
        "تحسن فهم المحتوى.",
        "الوقت اللازم لفهم الدرس.",
        "مستوى الاستقلالية.",
        "سهولة الوصول للمحتوى.",
        "رضا الطلاب والمعلمين.",
        "معدل استخدام المنصة.",
      ],
    },
    privacy: {
      kicker: "السلامة والخصوصية",
      title: "الطالب والمعلم في المركز",
      items: [
        "حماية بيانات الطلاب.",
        "تقليل جمع البيانات غير الضرورية.",
        "تصميم مناسب لذوي الإعاقة.",
        "عدم تقديم تشخيصات طبية.",
        "إبقاء الطالب والمعلم في مركز عملية التعلم.",
      ],
    },
    vision: {
      kicker: "الرؤية المستقبلية",
      title: "من صفحة في كتاب... إلى تجربة تعلم كاملة",
      p1: "لا يهدف فَهْم إلى إنشاء أداة مساعدة فقط.",
      p2: "الرؤية هي بناء بنية تعليمية تكيفية يمكنها تحويل المحتوى التعليمي التقليدي إلى تجارب شخصية تناسب احتياجات المتعلمين.",
      line: "من صفحة في كتاب... إلى تجربة تعلم كاملة.",
    },
    human: {
      kicker: "القيمة الإنسانية",
      title: "مشروع عن إتاحة المعرفة",
      p1: "فَهْم ليس مشروعًا عن الذكاء الاصطناعي فقط.",
      p2: "إنه مشروع عن إتاحة المعرفة.",
      p3: "لأن الطالب لا ينبغي أن يحتاج إلى شخص آخر حتى يفهم درسه.",
      closer: "لا نطلب من الطالب أن يتكيف مع المعرفة... بل نجعل المعرفة تتكيف معه.",
      cta: "اكتشف كيف يعمل فَهْم",
      ctaSecondary: "نموذج العمل والشراكة",
    },
    footer: {
      brand: "فَهْم | FAHM",
      blurb: "منصة الذكاء الاصطناعي للتعلّم التكيفي لذوي الإعاقة",
      copyright: "موقع تعريفي لفَهْم — للمدارس والمستثمرين والشركاء.",
    },
  },
  en: {
    meta: {
      title:
        "FAHM | فَهْم — AI platform for adaptive learning for people with disabilities",
      description:
        "FAHM is a smart educational platform that uses artificial intelligence to adapt educational content to the needs of students with disabilities.",
    },
    skip: "Skip to content",
    nav: {
      open: "Open menu",
      close: "Close menu",
      menu: "Menu",
      items: [
        { href: "#about", label: "About" },
        { href: "#problem", label: "Problem" },
        { href: "#solution", label: "Solution" },
        { href: "#features", label: "Features" },
        { href: "#how-it-works", label: "How it works" },
        { href: "#impact", label: "Impact" },
        { href: "#vision", label: "Vision" },
      ],
    },
    lang: {
      switchTo: "العربية",
      switchAria: "التبديل إلى العربية",
      current: "English",
    },
    hero: {
      brandAr: "فَهْم",
      brandEn: "FAHM",
      eyebrow: "A smart educational platform",
      subtitle: "The AI platform for adaptive learning for people with disabilities",
      slogan:
        "Every child deserves to understand, learn, and succeed, no matter how they learn.",
      primaryCta: "Discover FAHM",
      secondaryCta: "For schools and partners",
    },
    about: {
      kicker: "About the project",
      title: "Knowledge adapts to the student — not the other way around",
      p1: "FAHM (فَهْم) is a smart educational platform that uses artificial intelligence to adapt educational content to the needs of students with disabilities.",
      p2: "Instead of the student having to adapt to the book, FAHM adapts knowledge to the student.",
      p3: "The student photographs a page from their book or uploads it to the platform. The system then understands the texts, images, and educational illustrations, and re-presents the content more clearly and in a way that better suits their needs.",
    },
    problem: {
      kicker: "The problem",
      title: "One book… many different needs",
      lead: "Textbooks are often designed in a uniform way, while students’ abilities and needs differ.",
      intro: "A student with a disability may struggle with:",
      items: [
        "Reading dense text.",
        "Understanding drawings and diagrams.",
        "Focusing on the essential information.",
        "Accessing content without help from others.",
        "Dealing with content in the traditional way.",
      ],
      closer:
        "The problem is not the student’s ability to learn, but the way knowledge is presented to them.",
    },
    solution: {
      kicker: "The solution",
      title: "From a textbook page to an accessible learning experience",
      lead: "FAHM turns the educational page into an adaptive learning experience through:",
      steps: [
        { title: "Book image", hint: "Photograph or upload the page" },
        { title: "Understand the content", hint: "Text, images, and figures" },
        { title: "Analyze the student’s need", hint: "According to how they learn" },
        { title: "Adapt the knowledge", hint: "Without changing the curriculum" },
        { title: "An accessible experience", hint: "Read, listen, or interact" },
      ],
      note: "Without needing to redesign the book or change the curriculum.",
    },
    audiences: {
      kicker: "Target audiences",
      title: "Built for those whose path to knowledge is different",
      items: [
        "Students with visual disabilities.",
        "Students with dyslexia.",
        "Students with ADHD.",
        "Students with learning difficulties.",
      ],
      note: "It can later be expanded to serve a wider range of learners.",
    },
    features: {
      kicker: "Core features",
      title: "Seven capabilities that make a complete understanding experience",
      items: [
        {
          num: "01",
          title: "Smart understanding",
          body: "FAHM analyzes texts, images, and educational illustrations — not merely extracting text.",
        },
        {
          num: "02",
          title: "Adaptive learning",
          body: "It re-presents content according to the student’s needs instead of offering one experience for everyone.",
        },
        {
          num: "03",
          title: "Audio access",
          body: "Turning content into natural spoken explanation in Arabic using text-to-speech technologies.",
        },
        {
          num: "04",
          title: "Smart summarization",
          body: "Shortening lessons and complex content into clear, easy-to-understand points.",
        },
        {
          num: "05",
          title: "Accessible reading",
          body: "Reformatting content to improve readability, with features suited to students with dyslexia.",
        },
        {
          num: "06",
          title: "Understanding educational images",
          body: "Analyzing drawings, diagrams, and images and explaining their meaning to the student in a simplified way.",
        },
        {
          num: "07",
          title: "Smart assistant",
          body: "Enabling interaction with the content and asking for clarification, simplification, or examples.",
        },
      ],
    },
    how: {
      kicker: "How does the system work?",
      title: "Five steps from the page to understanding",
      steps: [
        "The student photographs the book page or uploads an image of it.",
        "Artificial intelligence analyzes the text, images, and visual elements.",
        "The system understands the educational content and identifies the important elements.",
        "The content is then adapted according to the student’s needs.",
        "The student receives an accessible educational experience that can be read, listened to, or interacted with.",
      ],
    },
    tech: {
      kicker: "Technology",
      title: "A stack that joins vision, language, and adaptive learning",
      items: [
        "Generative AI",
        "Computer Vision",
        "OCR",
        "Natural Language Processing",
        "Text-to-Speech",
        "Adaptive Learning",
        "Large Language Models",
      ],
      stackLabel: "Stack",
      stack:
        "Next.js + TypeScript + Tailwind CSS + Python/FastAPI + AI APIs + ElevenLabs",
    },
    difference: {
      kicker: "What makes FAHM different?",
      title: "From reading content to an adaptive learning engine",
      traditionalLead: "Most traditional access tools focus on reading content.",
      fahmLead: "FAHM focuses on understanding content and adapting it.",
      instead: "Instead of",
      offers: "It offers",
      traditionalPath: ["Read", "Listen"],
      fahmPath: ["See", "Understand", "Adapt", "Learn"],
      closer:
        "This transforms the platform from a content reader into an adaptive learning engine.",
      traditionalLabel: "Traditional tools",
      fahmLabel: "FAHM",
    },
    innovation: {
      kicker: "Innovation",
      title: "One page… a different experience for every student",
      lead: "The core innovation in FAHM is bringing together:",
      parts: [
        "Understanding text",
        "Understanding the image",
        "Generative AI",
        "Personalization",
        "Accessible access",
      ],
      join: "inside a single experience.",
      closer:
        "The same page can become a different experience according to the student’s need.",
    },
    impact: {
      kicker: "Expected impact",
      title: "Greater independence… closer understanding",
      items: [
        "Strengthening the independence of students with disabilities.",
        "Making access to knowledge easier.",
        "Improving understanding of educational content.",
        "Reducing reliance on human assistance.",
        "Supporting inclusive education.",
        "Narrowing the gap between the student and the content.",
      ],
      resultLabel: "Intended outcome",
      result:
        "A student who can access knowledge and understand it in a way that suits them.",
    },
    mvp: {
      kicker: "MVP prototype",
      title: "A working model that proves the idea is viable",
      lead: "A working prototype has been developed to prove the idea can be applied.",
      includes: "The prototype includes:",
      items: [
        "Uploading book pages.",
        "Analyzing content with artificial intelligence.",
        "Understanding texts and visual elements.",
        "Rewriting the content.",
        "Summarization.",
        "Audio output.",
        "An accessible educational experience.",
      ],
      closer:
        "The prototype is used to prove the idea and test the user experience before expanding into a complete educational platform.",
    },
    business: {
      kicker: "Business model",
      title: "Institutional subscription… then a wider network",
      primary: "An annual subscription for educational institutions",
      expand: "With the possibility of expanding in the future to:",
      items: [
        "Institutional licenses.",
        "Government partnerships.",
        "Integration with education platforms.",
        "Custom solutions for schools and special-education centers.",
      ],
    },
    roadmap: {
      kicker: "Expansion strategy",
      title: "From a defined sample to the Arab region",
      stages: [
        "Testing the platform with a defined sample of students with disabilities.",
        "Expanding to inclusive schools and special-education centers.",
        "Expanding across the Kingdom of Saudi Arabia.",
        "Integrating with the national education ecosystem.",
        "Expanding across the Gulf and the Arab region.",
      ],
    },
    metrics: {
      kicker: "Measuring impact",
      title: "What we measure to know that understanding is happening",
      items: [
        "Improved understanding of content.",
        "Time needed to understand the lesson.",
        "Level of independence.",
        "Ease of access to content.",
        "Student and teacher satisfaction.",
        "Platform usage rate.",
      ],
    },
    privacy: {
      kicker: "Safety and privacy",
      title: "The student and the teacher at the center",
      items: [
        "Protecting student data.",
        "Minimizing the collection of unnecessary data.",
        "Design suited to people with disabilities.",
        "Not providing medical diagnoses.",
        "Keeping the student and the teacher at the center of the learning process.",
      ],
    },
    vision: {
      kicker: "Future vision",
      title: "From a page in a book... to a complete learning experience",
      p1: "FAHM does not aim to create an assistive tool only.",
      p2: "The vision is to build an adaptive educational infrastructure that can turn traditional educational content into personal experiences that fit learners’ needs.",
      line: "From a page in a book... to a complete learning experience.",
    },
    human: {
      kicker: "Human value",
      title: "A project about making knowledge available",
      p1: "FAHM is not a project about artificial intelligence only.",
      p2: "It is a project about making knowledge available.",
      p3: "Because a student should not need another person in order to understand their lesson.",
      closer:
        "We do not ask the student to adapt to knowledge... we make knowledge adapt to them.",
      cta: "See how FAHM works",
      ctaSecondary: "Business model and partnership",
    },
    footer: {
      brand: "فَهْم | FAHM",
      blurb: "The AI platform for adaptive learning for people with disabilities",
      copyright: "A portfolio site for FAHM — for schools, investors, and partners.",
    },
  },
} as const;

export type Copy = (typeof content)[Locale];
